language: csharp

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "EAzBjuNuwqTjd5m+3tJJ1lcgFUjeTVGcD92VDPbO2Yd6FTv04PZo9XbwtusCAHlcemy+K4k16mPKrr/7N2EGbcOo9MdFiHfmZGvfj4YUrhWr46PhwedSfQm4MO9S2is4/KHvr4OeCNyn8qwP6n/avSGcMiI9krAjwcJdY3Ur98JOVObPE8023YMagQrJCLG7Uw5HtpcpMK0Y7PyNU6BxUNVQ6GLGK9FDJwPf1foOlj+DHNAyYH7pmebFkjMoNACc5XltFOFT+xwzgmJAzD/W+pg3w7K32wrDNUk7PmvHEItRF56oW8tsdaYOIVjoaqKKk/NV0PbhzQrwGeh802I0+mPCPzYwOyI1SfgtddMBF91uiqspGstIzF5eFScwgeAF1bOOMg5iNIC0ovsZ0TDVcP0T/vQUJ84zGZyUSz+5akw8ptN0XXLW5GLFVj8YhPOBysFhhj9ICfb4LxRi7bKbCd9SAlLt0ka/N8GtgOF30nNB/UmFPwWD2PQFCT4w7sUqOKCXPk6eLZ76dm3LL3TlFTCFm7RxJ3JoBY1UvaKdLxE2QBa3Owij61sDkBpTH1TUP2n3oFoD0aKCQ2lzMrC3rFBVGB8aBzDcOoz/lg5hgrnYfw7QEIKseNwCWYxfvzaiIhBDSuUUc1HyIW3JAZUmAnzD3ZtNN4eGo6G5zkE0oUU="

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make ; fi

addons:
  coverity_scan:

    # GitHub project metadata
    project:
      name: moto-timo/ironpython3
      version: 0.1
      description: Iron Python 3

    build_command: make

    branch_pattern: coverity_scan
